/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * 禁用媒体控件
 *
 * ### Errors
 *
 * 会在调用 API 失败时抛出错误
 */
export declare function disableSystemMedia(): void

/**
 * 启用媒体控件
 *
 * ### Errors
 *
 * 会在调用 API 失败时抛出错误
 */
export declare function enableSystemMedia(): void

/**
 * 初始化插件
 *
 * ### 参数
 *
 * * `log_dir` - 要把日志文件保存到的路径
 *
 * ### Errors
 *
 * 可能会在日志初始化失败，或者媒体控件初始化失败时抛出错误
 *
 * ### 备注
 *
 * 如果其他 API 调用失败，则只会打印日志并静默失败
 */
export declare function initialize(logDir: string): void

export interface MetadataParam {
  songName: string
  authorName: string
  albumName: string
  /** 封面的原始字节数据 */
  coverData?: Buffer
  /** Linux 平台在没有提供 `cover_data` 时使用的封面 HTTP URL */
  originalCoverUrl?: string
  /**
   * 网易云音乐中对应的曲目 ID
   *
   * ### 用途
   * - 以 "NCM-{ID}" 的格式上传到 SMTC 的 “流派” 字段
   * - MacOS 和 Linux 会使用此值来填充唯一的曲目 ID
   */
  ncmId?: number
  /**
   * 当前歌曲时长，单位是毫秒
   *
   * 用于 Linux、MacOS 的元数据更新。Windows 使用 [`TimelinePayload`] 的
   * `total_time` 字段。
   */
  duration?: number
}

export type PlaybackStatus =  'Playing'|
'Paused';

export interface PlayModePayload {
  isShuffling: boolean
  repeatMode: RepeatMode
}

export interface PlayStatePayload {
  status: PlaybackStatus
}

/**
 * 注册媒体控件的事件回调 (上一首、下一首、暂停、播放等)
 *
 * ### 参数
 *
 * `(event: SystemMediaEvent) => void`
 *
 * ### Errors
 *
 * 如果 N-API 创建线程安全函数失败，会抛出错误。通常不应该发生，除非 JS 环境已经销毁了
 */
export declare function registerEventHandler(callback: (arg: SystemMediaEvent) => void): void

export type RepeatMode =  'None'|
'Track'|
'List';

/** 关闭插件，清理资源 */
export declare function shutdown(): void

export interface SystemMediaEvent {
  type: SystemMediaEventType
  positionMs?: number
  rate?: number
  volume?: number
}

export type SystemMediaEventType =  'Play'|
'Pause'|
'Stop'|
'NextSong'|
'PreviousSong'|
'ToggleShuffle'|
'ToggleRepeat'|
'SetRate'|
'SetVolume'|
/** 绝对位置，毫秒 */
'Seek';

export interface TimelinePayload {
  /** 单位是毫秒 */
  currentTime: number
  /** 单位是毫秒 */
  totalTime: number
  /** 是否为 seek 操作触发的更新 */
  seeked?: boolean
}

/** 更新歌曲元数据 */
export declare function updateMetadata(payload: MetadataParam): void

/** 更新播放速率 */
export declare function updatePlaybackRate(rate: number): void

/** 更新播放模式 */
export declare function updatePlayMode(payload: PlayModePayload): void

/** 更新播放状态 (播放/暂停) */
export declare function updatePlayState(payload: PlayStatePayload): void

/** 更新进度信息 */
export declare function updateTimeline(payload: TimelinePayload): void

/** 更新音量 */
export declare function updateVolume(volume: number): void
