// 全球国家与地区数据列表 (ISO 3166-1 alpha-2)
export interface WorldCountry {
  code: string;
  name: string; // 法语
  nameEn: string;
  nameZh: string;
  flag: string;
}

export const ALL_WORLD_COUNTRIES: WorldCountry[] = [
  { code: "FR", name: "France", nameEn: "France", nameZh: "法国", flag: "🇫🇷" },
  { code: "US", name: "États-Unis", nameEn: "United States", nameZh: "美国", flag: "🇺🇸" },
  { code: "GB", name: "Royaume-Uni", nameEn: "United Kingdom", nameZh: "英国", flag: "🇬🇧" },
  { code: "CA", name: "Canada", nameEn: "Canada", nameZh: "加拿大", flag: "🇨🇦" },
  { code: "CN", name: "Chine", nameEn: "China", nameZh: "中国", flag: "🇨🇳" },
  { code: "DE", name: "Allemagne", nameEn: "Germany", nameZh: "德国", flag: "🇩🇪" },
  { code: "ES", name: "Espagne", nameEn: "Spain", nameZh: "西班牙", flag: "🇪🇸" },
  { code: "IT", name: "Italie", nameEn: "Italy", nameZh: "意大利", flag: "🇮🇹" },
  { code: "BE", name: "Belgique", nameEn: "Belgium", nameZh: "比利时", flag: "🇧🇪" },
  { code: "CH", name: "Suisse", nameEn: "Switzerland", nameZh: "瑞士", flag: "🇨🇭" },
  { code: "SN", name: "Sénégal", nameEn: "Senegal", nameZh: "塞内加尔", flag: "🇸🇳" },
  { code: "CI", name: "Côte d'Ivoire", nameEn: "Ivory Coast", nameZh: "科特迪瓦", flag: "🇨🇮" },
  { code: "JP", name: "Japon", nameEn: "Japan", nameZh: "日本", flag: "🇯🇵" },
  { code: "BR", name: "Brésil", nameEn: "Brazil", nameZh: "巴西", flag: "🇧🇷" },
  { code: "MA", name: "Maroc", nameEn: "Morocco", nameZh: "摩洛哥", flag: "🇲🇦" },
  { code: "DZ", name: "Algérie", nameEn: "Algeria", nameZh: "阿尔及利亚", flag: "🇩🇿" },
  { code: "TN", name: "Tunisie", nameEn: "Tunisia", nameZh: "突尼斯", flag: "🇹🇳" },
  { code: "CM", name: "Cameroun", nameEn: "Cameroon", nameZh: "喀麦隆", flag: "🇨🇲" },
  { code: "CD", name: "RD Congo", nameEn: "DR Congo", nameZh: "刚果民主共和国", flag: "🇨🇩" },
  { code: "CG", name: "Congo", nameEn: "Republic of the Congo", nameZh: "刚果共和国", flag: "🇨🇬" },
  { code: "MG", name: "Madagascar", nameEn: "Madagascar", nameZh: "马达加斯加", flag: "🇲🇬" },
  { code: "ML", name: "Mali", nameEn: "Mali", nameZh: "马里", flag: "🇲🇱" },
  { code: "GN", name: "Guinée", nameEn: "Guinea", nameZh: "几内亚", flag: "🇬🇳" },
  { code: "BF", name: "Burkina Faso", nameEn: "Burkina Faso", nameZh: "布基纳法索", flag: "🇧🇫" },
  { code: "NE", name: "Niger", nameEn: "Niger", nameZh: "尼日尔", flag: "🇳🇪" },
  { code: "TG", name: "Togo", nameEn: "Togo", nameZh: "多哥", flag: "🇹🇬" },
  { code: "BJ", name: "Bénin", nameEn: "Benin", nameZh: "贝宁", flag: "🇧🇯" },
  { code: "GA", name: "Gabon", nameEn: "Gabon", nameZh: "加蓬", flag: "🇬🇦" },
  { code: "TD", name: "Tchad", nameEn: "Chad", nameZh: "乍得", flag: "🇹🇩" },
  {
    code: "CF",
    name: "Centrafrique",
    nameEn: "Central African Republic",
    nameZh: "中非",
    flag: "🇨🇫",
  },
  { code: "RW", name: "Rwanda", nameEn: "Rwanda", nameZh: "卢旺达", flag: "🇷🇼" },
  { code: "BI", name: "Burundi", nameEn: "Burundi", nameZh: "布隆迪", flag: "🇧🇮" },
  { code: "DJ", name: "Djibouti", nameEn: "Djibouti", nameZh: "吉布提", flag: "🇩🇯" },
  { code: "HT", name: "Haïti", nameEn: "Haiti", nameZh: "海地", flag: "🇭🇹" },
  { code: "MU", name: "Maurice", nameEn: "Mauritius", nameZh: "毛里求斯", flag: "🇲🇺" },
  { code: "SC", name: "Seychelles", nameEn: "Seychelles", nameZh: "塞舌尔", flag: "🇸🇨" },
  { code: "MX", name: "Mexique", nameEn: "Mexico", nameZh: "墨西哥", flag: "🇲🇽" },
  { code: "AR", name: "Argentine", nameEn: "Argentina", nameZh: "阿根廷", flag: "🇦🇷" },
  { code: "CO", name: "Colombie", nameEn: "Colombia", nameZh: "哥伦比亚", flag: "🇨🇴" },
  { code: "CL", name: "Chili", nameEn: "Chile", nameZh: "智利", flag: "🇨🇱" },
  { code: "PE", name: "Pérou", nameEn: "Peru", nameZh: "秘鲁", flag: "🇵🇪" },
  { code: "VE", name: "Venezuela", nameEn: "Venezuela", nameZh: "委内瑞拉", flag: "🇻🇪" },
  { code: "EC", name: "Équateur", nameEn: "Ecuador", nameZh: "厄瓜多尔", flag: "🇪🇨" },
  { code: "BO", name: "Bolivie", nameEn: "Bolivia", nameZh: "玻利维亚", flag: "🇧🇴" },
  { code: "UY", name: "Uruguay", nameEn: "Uruguay", nameZh: "乌拉圭", flag: "🇺🇾" },
  { code: "PY", name: "Paraguay", nameEn: "Paraguay", nameZh: "巴拉圭", flag: "🇵🇾" },
  { code: "CU", name: "Cuba", nameEn: "Cuba", nameZh: "古巴", flag: "🇨🇺" },
  {
    code: "DO",
    name: "Rép. Dominicaine",
    nameEn: "Dominican Republic",
    nameZh: "多米尼加",
    flag: "🇩🇴",
  },
  { code: "CR", name: "Costa Rica", nameEn: "Costa Rica", nameZh: "哥斯达黎加", flag: "🇨🇷" },
  { code: "PA", name: "Panama", nameEn: "Panama", nameZh: "巴拿马", flag: "🇵🇦" },
  { code: "PT", name: "Portugal", nameEn: "Portugal", nameZh: "葡萄牙", flag: "🇵🇹" },
  { code: "NL", name: "Pays-Bas", nameEn: "Netherlands", nameZh: "荷兰", flag: "🇳🇱" },
  { code: "IE", name: "Irlande", nameEn: "Ireland", nameZh: "爱尔兰", flag: "🇮🇪" },
  { code: "SE", name: "Suède", nameEn: "Sweden", nameZh: "瑞典", flag: "🇸🇪" },
  { code: "NO", name: "Norvège", nameEn: "Norway", nameZh: "挪威", flag: "🇳🇴" },
  { code: "DK", name: "Danemark", nameEn: "Denmark", nameZh: "丹麦", flag: "🇩🇰" },
  { code: "FI", name: "Finlande", nameEn: "Finland", nameZh: "芬兰", flag: "🇫🇮" },
  { code: "PL", name: "Pologne", nameEn: "Poland", nameZh: "波兰", flag: "🇵🇱" },
  { code: "AT", name: "Autriche", nameEn: "Austria", nameZh: "奥地利", flag: "🇦🇹" },
  { code: "GR", name: "Grèce", nameEn: "Greece", nameZh: "希腊", flag: "🇬🇷" },
  { code: "TR", name: "Turquie", nameEn: "Turkey", nameZh: "土耳其", flag: "🇹🇷" },
  { code: "RU", name: "Russie", nameEn: "Russia", nameZh: "俄罗斯", flag: "🇷🇺" },
  { code: "UA", name: "Ukraine", nameEn: "Ukraine", nameZh: "乌克兰", flag: "🇺🇦" },
  { code: "RO", name: "Roumanie", nameEn: "Romania", nameZh: "罗马尼亚", flag: "🇷🇴" },
  { code: "HU", name: "Hongrie", nameEn: "Hungary", nameZh: "匈牙利", flag: "🇭🇺" },
  { code: "CZ", name: "Tchéquie", nameEn: "Czechia", nameZh: "捷克", flag: "🇨🇿" },
  { code: "SK", name: "Slovaquie", nameEn: "Slovakia", nameZh: "斯洛伐克", flag: "🇸🇰" },
  { code: "SI", name: "Slovénie", nameEn: "Slovenia", nameZh: "斯洛文尼亚", flag: "🇸🇮" },
  { code: "HR", name: "Croatie", nameEn: "Croatia", nameZh: "克罗地亚", flag: "🇭🇷" },
  { code: "BA", name: "Bosnie", nameEn: "Bosnia", nameZh: "波黑", flag: "🇧🇦" },
  { code: "RS", name: "Serbie", nameEn: "Serbia", nameZh: "塞尔维亚", flag: "🇷🇸" },
  { code: "ME", name: "Monténégro", nameEn: "Montenegro", nameZh: "黑山", flag: "🇲🇪" },
  { code: "MK", name: "Macédoine", nameEn: "North Macedonia", nameZh: "北马其顿", flag: "🇲🇰" },
  { code: "AL", name: "Albanie", nameEn: "Albania", nameZh: "阿尔巴尼亚", flag: "🇦🇱" },
  { code: "SA", name: "Arabie Saoudite", nameEn: "Saudi Arabia", nameZh: "沙特", flag: "🇸🇦" },
  { code: "AE", name: "Émirats Arabes Unis", nameEn: "UAE", nameZh: "阿联酋", flag: "🇦🇪" },
  { code: "QA", name: "Qatar", nameEn: "Qatar", nameZh: "卡塔尔", flag: "🇶🇦" },
  { code: "KW", name: "Koweït", nameEn: "Kuwait", nameZh: "科威特", flag: "🇰🇼" },
  { code: "IL", name: "Israël", nameEn: "Israel", nameZh: "以色列", flag: "🇮🇱" },
  { code: "IR", name: "Iran", nameEn: "Iran", nameZh: "伊朗", flag: "🇮🇷" },
  { code: "IQ", name: "Irak", nameEn: "Iraq", nameZh: "伊拉克", flag: "🇮🇶" },
  { code: "JO", name: "Jordanie", nameEn: "Jordan", nameZh: "约旦", flag: "🇯🇴" },
  { code: "LB", name: "Liban", nameEn: "Lebanon", nameZh: "黎巴嫩", flag: "🇱🇧" },
  { code: "SY", name: "Syrie", nameEn: "Syria", nameZh: "叙利亚", flag: "🇸🇾" },
  { code: "YE", name: "Yémen", nameEn: "Yemen", nameZh: "也门", flag: "🇾🇪" },
  { code: "OM", name: "Oman", nameEn: "Oman", nameZh: "阿曼", flag: "🇴🇲" },
  { code: "KR", name: "Corée du Sud", nameEn: "South Korea", nameZh: "韩国", flag: "🇰🇷" },
  { code: "IN", name: "Inde", nameEn: "India", nameZh: "印度", flag: "🇮🇳" },
  { code: "TW", name: "Taïwan", nameEn: "Taiwan", nameZh: "台湾", flag: "🇹🇼" },
  { code: "TH", name: "Thaïlande", nameEn: "Thailand", nameZh: "泰国", flag: "🇹🇭" },
  { code: "VN", name: "Vietnam", nameEn: "Vietnam", nameZh: "越南", flag: "🇻🇳" },
  { code: "ID", name: "Indonésie", nameEn: "Indonesia", nameZh: "印度尼西亚", flag: "🇮🇩" },
  { code: "MY", name: "Malaisie", nameEn: "Malaysia", nameZh: "马来西亚", flag: "🇲🇾" },
  { code: "SG", name: "Singapour", nameEn: "Singapore", nameZh: "新加坡", flag: "🇸🇬" },
  { code: "PH", name: "Philippines", nameEn: "Philippines", nameZh: "菲律宾", flag: "🇵🇭" },
  { code: "KH", name: "Cambodge", nameEn: "Cambodia", nameZh: "柬埔寨", flag: "🇰🇭" },
  { code: "LA", name: "Laos", nameEn: "Laos", nameZh: "老挝", flag: "🇱🇦" },
  { code: "MM", name: "Birmanie", nameEn: "Myanmar", nameZh: "缅甸", flag: "🇲🇲" },
  { code: "BD", name: "Bangladesh", nameEn: "Bangladesh", nameZh: "孟加拉", flag: "🇧🇩" },
  { code: "LK", name: "Sri Lanka", nameEn: "Sri Lanka", nameZh: "斯里兰卡", flag: "🇱🇰" },
  { code: "NP", name: "Népal", nameEn: "Nepal", nameZh: "尼泊尔", flag: "🇳🇵" },
  { code: "PK", name: "Pakistan", nameEn: "Pakistan", nameZh: "巴基斯坦", flag: "🇵🇰" },
  { code: "AF", name: "Afghanistan", nameEn: "Afghanistan", nameZh: "阿富汗", flag: "🇦🇫" },
  { code: "KZ", name: "Kazakhstan", nameEn: "Kazakhstan", nameZh: "哈萨克斯坦", flag: "🇰🇿" },
  { code: "UZ", name: "Ouzbékistan", nameEn: "Uzbekistan", nameZh: "乌兹别克斯坦", flag: "🇺🇿" },
  { code: "AU", name: "Australie", nameEn: "Australia", nameZh: "澳大利亚", flag: "🇦🇺" },
  { code: "NZ", name: "Nouvelle-Zélande", nameEn: "New Zealand", nameZh: "新西兰", flag: "🇳🇿" },
  { code: "JM", name: "Jamaïque", nameEn: "Jamaica", nameZh: "牙买加", flag: "🇯🇲" },
  {
    code: "TT",
    name: "Trinité-et-Tobago",
    nameEn: "Trinidad and Tobago",
    nameZh: "特立尼达和多巴哥",
    flag: "🇹🇹",
  },
  { code: "BB", name: "Barbade", nameEn: "Barbados", nameZh: "巴巴多斯", flag: "🇧🇧" },
  { code: "BS", name: "Bahamas", nameEn: "Bahamas", nameZh: "巴哈马", flag: "🇧🇸" },
  { code: "GT", name: "Guatemala", nameEn: "Guatemala", nameZh: "危地马拉", flag: "🇬🇹" },
  { code: "HN", name: "Honduras", nameEn: "Honduras", nameZh: "洪都拉斯", flag: "🇭🇳" },
  { code: "SV", name: "Salvador", nameEn: "El Salvador", nameZh: "萨尔瓦多", flag: "🇸🇻" },
  { code: "NI", name: "Nicaragua", nameEn: "Nicaragua", nameZh: "尼加拉瓜", flag: "🇳🇮" },
  { code: "PR", name: "Porto Rico", nameEn: "Puerto Rico", nameZh: "波多黎各", flag: "🇵🇷" },
  { code: "GY", name: "Guyana", nameEn: "Guyana", nameZh: "圭亚那", flag: "🇬🇾" },
  { code: "SR", name: "Suriname", nameEn: "Suriname", nameZh: "苏里南", flag: "🇸🇷" },
  { code: "NG", name: "Nigeria", nameEn: "Nigeria", nameZh: "尼日利亚", flag: "🇳🇬" },
  { code: "ZA", name: "Afrique du Sud", nameEn: "South Africa", nameZh: "南非", flag: "🇿🇦" },
  { code: "EG", name: "Égypte", nameEn: "Egypt", nameZh: "埃及", flag: "🇪🇬" },
  { code: "ET", name: "Éthiopie", nameEn: "Ethiopia", nameZh: "埃塞俄比亚", flag: "🇪🇹" },
  { code: "KE", name: "Kenya", nameEn: "Kenya", nameZh: "肯尼亚", flag: "🇰🇪" },
  { code: "TZ", name: "Tanzanie", nameEn: "Tanzania", nameZh: "坦桑尼亚", flag: "🇹🇿" },
  { code: "UG", name: "Ouganda", nameEn: "Uganda", nameZh: "乌干达", flag: "🇺🇬" },
  { code: "GH", name: "Ghana", nameEn: "Ghana", nameZh: "加纳", flag: "🇬🇭" },
  { code: "ZM", name: "Zambie", nameEn: "Zambia", nameZh: "赞比亚", flag: "🇿🇲" },
  { code: "ZW", name: "Zimbabwe", nameEn: "Zimbabwe", nameZh: "津巴布韦", flag: "🇿🇼" },
  { code: "MZ", name: "Mozambique", nameEn: "Mozambique", nameZh: "莫桑比克", flag: "🇲🇿" },
  { code: "AO", name: "Angola", nameEn: "Angola", nameZh: "安哥拉", flag: "🇦🇴" },
  { code: "NA", name: "Namibie", nameEn: "Namibia", nameZh: "纳米比亚", flag: "🇳🇦" },
  { code: "BW", name: "Botswana", nameEn: "Botswana", nameZh: "博茨瓦纳", flag: "🇧🇼" },
  { code: "LY", name: "Libye", nameEn: "Libya", nameZh: "利比亚", flag: "🇱🇾" },
  { code: "SD", name: "Soudan", nameEn: "Sudan", nameZh: "苏丹", flag: "🇸🇩" },
  { code: "SO", name: "Somalie", nameEn: "Somalia", nameZh: "索马里", flag: "🇸🇴" },
  { code: "MR", name: "Mauritanie", nameEn: "Mauritania", nameZh: "毛里塔尼亚", flag: "🇲🇷" },
  { code: "SL", name: "Sierra Leone", nameEn: "Sierra Leone", nameZh: "塞拉利昂", flag: "🇸🇱" },
  { code: "LR", name: "Libéria", nameEn: "Liberia", nameZh: "利比里亚", flag: "🇱🇷" },
  { code: "GW", name: "Guinée-Bissau", nameEn: "Guinea-Bissau", nameZh: "几内亚比绍", flag: "🇬🇼" },
  { code: "HK", name: "Hong Kong", nameEn: "Hong Kong", nameZh: "中国香港", flag: "🇭🇰" },
  { code: "MO", name: "Macao", nameEn: "Macao", nameZh: "中国澳门", flag: "🇲🇴" },
  { code: "MN", name: "Mongolie", nameEn: "Mongolia", nameZh: "蒙古", flag: "🇲🇳" },
  { code: "FJ", name: "Fidji", nameEn: "Fiji", nameZh: "斐济", flag: "🇫🇯" },
  {
    code: "PG",
    name: "Papouasie-Nouv.-Guinée",
    nameEn: "Papua New Guinea",
    nameZh: "巴布亚新几内亚",
    flag: "🇵🇬",
  },
  {
    code: "NC",
    name: "Nouvelle-Calédonie",
    nameEn: "New Caledonia",
    nameZh: "新喀里多尼亚",
    flag: "🇳🇨",
  },
  {
    code: "PF",
    name: "Polynésie française",
    nameEn: "French Polynesia",
    nameZh: "法属波利尼西亚",
    flag: "🇵🇫",
  },
  { code: "RE", name: "La Réunion", nameEn: "Reunion", nameZh: "留尼汪", flag: "🇷🇪" },
  { code: "GP", name: "Guadeloupe", nameEn: "Guadeloupe", nameZh: "瓜德罗普", flag: "🇬🇵" },
  { code: "MQ", name: "Martinique", nameEn: "Martinique", nameZh: "马提尼克", flag: "🇲🇶" },
  { code: "GF", name: "Guyane", nameEn: "French Guiana", nameZh: "法属圭亚那", flag: "🇬🇫" },
  { code: "YT", name: "Mayotte", nameEn: "Mayotte", nameZh: "马约特", flag: "🇾🇹" },
];

// 获取根据语言格式化并排序的国家列表
export const getFormattedWorldCountries = (
  lang: string = "fr",
): Array<{ code: string; name: string; flag: string }> => {
  return ALL_WORLD_COUNTRIES.map((c) => {
    let name = c.name;
    if (lang === "en") name = c.nameEn;
    else if (lang === "zh") name = c.nameZh;
    return {
      code: c.code,
      name,
      flag: c.flag,
    };
  });
};

// 获取国家名称
export const getCountryNameByCode = (code: string, lang: string = "fr"): string => {
  const found = ALL_WORLD_COUNTRIES.find((c) => c.code.toUpperCase() === code.toUpperCase());
  if (!found) return code;
  if (lang === "en") return found.nameEn;
  if (lang === "zh") return found.nameZh;
  return found.name;
};
