blank_issues_enabled: false
contact_links:
  - name: 常见问题
    url: https://ccnp30z5li2m.feishu.cn/wiki/JWDdw646Ti68EDklHF5cCjpQnUc
    about: 这里可能有你想问的问题
  - name: 提问的艺术
    url: https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md
    about: 默认所有 Issues 发起者均已了解此处的内容
